Resources:
  AardvarkUser:
    Type: AWS::IAM::User
  AardvarkKey:
    Type: AWS::IAM::AccessKey
    Properties:
      UserName: !Ref 'AardvarkUser'
  AardvarkSNSTopic:
    Type: 'AWS::SNS::Topic'
    Properties:
      DisplayName: Cloud components for the Aardvark Arduino demo
      Subscription:
        -
          Endpoint: '{{resolve:ssm:/Aardvark/PhoneNumber:1}}'
          Protocol: sms
      Tags:
        -
          Key: Project
          Value: aardvark
Outputs:
  TopicArn:
    Value: !Ref 'AardvarkSNSTopic'
    Description: The ARN of the deployed SNS topic
  # AccessKey:
  #   Value: !Ref 'CFNKeys'
  #   Description: AWSAccessKeyId of new user
  # SecretKey:
  #   Value: !GetAtt [CFNKeys, SecretAccessKey]
  #   Description: AWSSecretAccessKey of new user
