AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  Password:
    NoEcho: 'true'
    Type: String
    Description: New account password
    MinLength: '1'
    MaxLength: '41'
    ConstraintDescription: the password must be between 1 and 41 characters
Resources:
  AardvarkUser:
    Type: AWS::IAM::User
    Properties:
      LoginProfile:
        Password: !Ref 'Password'

  AardvarkKey:
    Type: AWS::IAM::AccessKey
    Properties:
      UserName: !Ref 'AardvarkUser'

  AardvarkUserPolicies:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: AardvarkUser
      PolicyDocument:
        Statement:
        - Effect: Allow
          Action: ['SNS:Publish']
          Resource: !Ref AardvarkSnsTopic
      Users: [!Ref 'AardvarkUser']

  AardvarkSnsTopic:
    Type: 'AWS::SNS::Topic'
    Properties:
      DisplayName: Cloud components for the Aardvark Arduino demo
      Subscription:
        -
          Endpoint: '{{resolve:ssm:/Aardvark/PhoneNumber:1}}'
          Protocol: sms
Outputs:
  TopicArn:
    Value: !Ref 'AardvarkSnsTopic'
    Description: The ARN of the deployed SNS topic
  AccessKey:
    Value: !Ref 'AardvarkKey'
    Description: AWSAccessKeyId of new user
  SecretKey:
    Value: !GetAtt [AardvarkKey, SecretAccessKey]
    Description: AWSSecretAccessKey of new user
